[package]
name = "areview"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fnv = "1.0"
nannou = "0.18"
once_cell = "1.15"
regex = "1.6"

[profile.release]
lto = true
